blank_issues_enabled: false
contact_links:
  - name: 📢 Community Support
    url: https://github.com/SCP-Foundation-Minecraft-Mods
    about: Visit our GitHub org to browse all mods and their discussions.
